name: SynapseOS Buildbot

# Контроль событий при которых будет сборка
on:
  # В нашем случае это push в ветку master
  push:
    tags:
        - "v*"
    branches: [ "master" ]

  schedule: # Минута   Час        День       Месяц      День недели
    - cron:   '0        4        *           *         *'
  
  workflow_dispatch:

# Выполнение рабочего процесса состоит из одного или нескольких заданий, которые могут выполняться последовательно или параллельно
jobs:
  build:
    #  Все будет работать на последней версии Ubuntu
    runs-on: ubuntu-latest

    # Шаги представляют собой последовательность задач, которые будут выполняться как часть задания
    steps:
      - uses: actions/checkout@v3

      # Установка зависимостей
      - name: Installing
        run: |
          sudo apt install python3 build-essential xorriso mtools fasm zip doxygen
          
      # Запуск сборки ядра
      - name: Building  kernel
        run: python3 scripts/build.py

      # Проверка релиза
      - name: Check publish
        run: |
          echo "done!"
          ls isodir/boot/
          ls

      # Публикация релиза
      - name: Publish release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-unstable"
          prerelease: true
          title: "[Автосборка] Нестабильный релиз"
          description: "Внимание! Данный релиз собран из последних изменений в ядре! Это не окончательная версия содержит ошибки и не рекомендуется к запуску без проверки на виртуальной машине."
          files: |
            LICENSE
            SynapseOS-limine.iso
            isodir/boot/kernel.elf
            doxygen/rtf/refman.rtf
