name: SynapseOS Buildbot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install python3, grub-pc-bin, xorriso, mtools
      - name: Install python3, grub-pc-bin, xorriso, mtools
        run: sudo apt install python3 grub-pc-bin xorriso mtools

      # Download i686-elf-tools
      - name: Download i686-elf-tools
        run: |
          wget -nv https://github.com/lordmilko/i686-elf-tools/releases/download/7.1.0/i686-elf-tools-linux.zip
          sudo unzip i686-elf-tools-linux.zip -d /usr/local
          rm i686-elf-tools-linux.zip
      # Run ./build-actions.sh
      - name: Run build
        run: python3 build.py kernel iso

      - name: Create a Release
		uses: elgohr/Github-Release-Action@v4
			env:
				GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
			with:
				title: Autobuild
