name: SynapseOS only gcc

# Контроль событий при которых будет сборка
on:
  workflow_dispatch:

# Выполнение рабочего процесса состоит из одного или нескольких заданий, которые могут выполняться последовательно или параллельно
jobs:
  build:
    #  Все будет работать на последней версии Ubuntu
    runs-on: ubuntu-latest

    # Шаги представляют собой последовательность задач, которые будут выполняться как часть задания
    steps:
      - uses: actions/checkout@v3

      # Установка зависимостей
      - name: Installing
        run: |
          sudo apt install python3 build-essential xorriso mtools gcc

      # Сборка doxygen
      - name: Сборка doxygen
        run: |
          wget https://www.doxygen.nl/files/doxygen-1.9.5.linux.bin.tar.gz
          tar -xzf  doxygen-1.9.5.linux.bin.tar.gz>null
          cd doxygen-1.9.5/
          sudo make install
          cd ..

      # Установка limine
      - name: Limine
        run: |
          git clone https://github.com/limine-bootloader/limine.git --branch=v3.0-branch-binary --depth=1
          make -C limine
          cp limine/BOOTIA32.EFI limine/BOOTX64.EFI limine/limine-cd-efi.bin limine/limine.sys limine/limine-cd.bin isodir/
      # Запуск сборки ядра
      - name: Building  kernel
        run: | 
          python3 scripts/build.py -noqemu 1 -compiler "gcc -m32" -linker "ld -m elf_i386"
  
      # Проверка релиза
      - name: Check publish
        run: |
          echo "done!"
          ls

      # Публикация релиза
      - name: Publish test release 
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-unstable-test"
          prerelease: true
          title: "[Автосборка] Экспериментальный релиз"
          description: "Внимание! Данный релиз собран из последних изменений в ядре! Это не окончательная версия содержит ошибки и не рекомендуется к запуску без проверки на виртуальной машине."
          files: |
            LICENSE
            SynapseOS-limine.iso
            isodir/boot/kernel.elf
            doxygen/rtf/refman.rtf
