name: SynapseOS Pull Requests

# Контроль событий при которых будет сборка
on:
  # В нашем случае это push в ветку master
  #push:
  #  tags:
  #      - "v*"
  #  branches: [ "master" ]
  pull_request:
    tags:
        - "v*"
    branches: [ "master" ]
  # Позволяет запускать этот рабочий процесс вручную на вкладке Actions
  workflow_dispatch:


# Выполнение рабочего процесса состоит из одного или нескольких заданий, которые могут выполняться последовательно или параллельно
jobs:
  build:
    #  Все будет работать на последней версии Ubuntu
    runs-on: ubuntu-latest

    # Шаги представляют собой последовательность задач, которые будут выполняться как часть задания
    steps:
      - uses: actions/checkout@v3

      # Установка зависимостей
      - name: Installing
        run: |
          sudo apt install python3 build-essential xorriso mtools
          wget -nv https://github.com/lordmilko/i686-elf-tools/releases/download/7.1.0/i686-elf-tools-linux.zip
          sudo unzip i686-elf-tools-linux.zip -d /usr/local
          rm i686-elf-tools-linux.zip

      # Сборка doxygen
      - name: Сборка doxygen
        run: |
          wget https://www.doxygen.nl/files/doxygen-1.9.5.linux.bin.tar.gz
          tar -xzf  doxygen-1.9.5.linux.bin.tar.gz>null
          cd doxygen-1.9.5/
          sudo make install
          cd ..

      # Установка limine
      - name: Limine
        run: |
          git clone https://github.com/limine-bootloader/limine.git --branch=v3.0-branch-binary --depth=1
          make -C limine
          cp limine/BOOTIA32.EFI limine/BOOTX64.EFI limine/limine-cd-efi.bin limine/limine.sys limine/limine-cd.bin isodir/
          cp limine/limine-deploy ./
          
      # Запуск сборки ядра
      - name: Building  kernel
        run: | 
          python3 scripts/build.py -noqemu 1 -limine "./limine-deploy" -docs 1
          
  
      # Проверка релиза
      - name: Check publish
        run: |
          echo "done!"
          ls
